# Generated by Django 4.0.10 on 2024-01-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='complete_by',
            field=models.DateTimeField(null=True),
        ),
    ]
